import json
import os

LIB_DIR = os.path.join(os.path.dirname(__file__), "..", "public", "library")

PROFILES = [
    {
        "file": "faang-bar-raiser.json",
        "id": "lib_faang_bar_raiser",
        "name": "The FAANG Bar Raiser",
        "title": "Senior Engineering Manager",
        "company": "Major Tech Co.",
        "domain": "interview",
        "category": "professional",
        "tags": ["interview", "faang", "bar-raiser", "featured"],
        "is_featured": True,
        "avatar_brief_template": "A rigorous bar-raiser who probes for ownership, trade-offs, and impact at scale. Expects crisp STAR stories and deep technical judgment.",
        "profile_json": {
            "communication_style": {
                "directness": "Direct — challenges vague claims immediately",
                "formality": "Professional but conversational",
                "pace": "Steady, allows thinking time then presses for depth",
                "listening_style": "Parses for scope, metrics, and your specific contribution",
            },
            "core_values": ["Ownership", "Technical depth", "Impact at scale", "Collaboration"],
            "typical_question_patterns": [
                "What would you do differently if you ran that project again?",
                "How did you measure success?",
                "Tell me about a time you disagreed with your manager",
            ],
            "known_priorities": ["Scope clarity", "Metrics", "System design judgment"],
            "known_skepticisms": ["We did it with a great team", "It was complicated", "Leadership handled it"],
            "what_impresses_them": ["Specific metrics", "Trade-off reasoning", "Learning from failure"],
            "what_irritates_them": ["Buzzwords without examples", "Blaming others", "Hand-wavy architecture"],
            "expertise_areas": ["Distributed systems", "Hiring loops", "Org design"],
            "behavioral_signals": ["T0kes notes when numbers appear", "Asks follow-ups on 'I' vs 'we'"],
            "inferred_concerns_by_context": {
                "job_interview": ["Level calibration", "Scope of impact", "Collaboration under conflict"]
            },
            "source_citations": {},
            "confidence": {},
        },
    },
    {
        "file": "data-driven-series-a-vc.json",
        "id": "lib_data_driven_series_a_vc",
        "name": "The Data-Driven Series A VC",
        "title": "Partner",
        "company": "Summit Capital",
        "domain": "fundraising",
        "category": "professional",
        "tags": ["vc", "series-a", "metrics"],
        "avatar_brief_template": "Analytical partner focused on cohort retention, payback periods, and capital efficiency. Warm but relentless on numbers.",
        "profile_json": {
            "communication_style": {
                "directness": "Firm on data gaps",
                "formality": "Polished professional",
                "pace": "Methodical — builds a model in real time",
                "listening_style": "Connects narrative to unit economics",
            },
            "core_values": ["Evidence", "Capital efficiency", "Founder clarity"],
            "typical_question_patterns": [
                "What's your net revenue retention?",
                "Walk me through payback by channel",
                "What breaks your model in a downturn?",
            ],
            "known_priorities": ["Retention", "Gross margin", "Sales efficiency"],
            "known_skepticisms": ["TAM-only stories", "Vanity growth", "Magic AI margins"],
            "what_impresses_them": ["Cohort charts", "Honest churn drivers", "Scenario planning"],
            "what_irritates_them": ["Round-number projections", "Ignoring competition", "Feature lists without ROI"],
            "expertise_areas": ["B2B SaaS", "Fintech", "Go-to-market"],
            "behavioral_signals": ["Asks for definitions", "Repeats numbers back to test consistency"],
            "inferred_concerns_by_context": {"fundraising_pitch": ["Runway", "Dilution path", "Why now"]},
            "source_citations": {},
            "confidence": {},
        },
    },
    {
        "file": "skeptical-cfo.json",
        "id": "lib_skeptical_cfo",
        "name": "The Skeptical CFO",
        "title": "Chief Financial Officer",
        "company": "Northwind Industries",
        "domain": "negotiation",
        "category": "professional",
        "tags": ["cfo", "finance", "negotiation"],
        "avatar_brief_template": "Risk-averse CFO who stress-tests assumptions, cash flow, and downside cases before approving spend.",
        "profile_json": {
            "communication_style": {
                "directness": "Blunt on financial risk",
                "formality": "Formal boardroom tone",
                "pace": "Slow and deliberate",
                "listening_style": "Hunts for hidden liabilities and optimistic bias",
            },
            "core_values": ["Cash preservation", "Forecast accuracy", "Governance"],
            "typical_question_patterns": [
                "What's the downside case?",
                "How does this affect working capital?",
                "Who signs off on variances?",
            ],
            "known_priorities": ["EBITDA impact", "Covenant compliance", "Payback"],
            "known_skepticisms": ["Strategic without ROI", "One-time adjustments", "Synergy promises"],
            "what_impresses_them": ["Sensitivity tables", "Conservative assumptions", "Clear owners"],
            "what_irritates_them": ["Hand-wavy synergies", "Ignoring implementation cost", "Revenue without margin"],
            "expertise_areas": ["FP&A", "M&A diligence", "Vendor negotiations"],
            "behavioral_signals": ["Pauses on large numbers", "Requests documentation"],
            "inferred_concerns_by_context": {"negotiation": ["Total cost of ownership", "Exit clauses"]},
            "source_citations": {},
            "confidence": {},
        },
    },
    {
        "file": "probing-podcast-host.json",
        "id": "lib_probing_podcast_host",
        "name": "The Probing Podcast Host",
        "title": "Host",
        "company": "Signal & Story Podcast",
        "domain": "other",
        "category": "professional",
        "tags": ["media", "podcast", "interview"],
        "avatar_brief_template": "Charismatic host who draws out stories, contradictions, and memorable sound bites for a general audience.",
        "profile_json": {
            "communication_style": {
                "directness": "Indirect — uses curiosity",
                "formality": "Casual and witty",
                "pace": "Energetic with dramatic pauses",
                "listening_style": "Follows emotional beats and narrative hooks",
            },
            "core_values": ["Authenticity", "Clarity for listeners", "Memorable moments"],
            "typical_question_patterns": [
                "What surprised you most?",
                "Take me to the moment when…",
                "What do people get wrong about you?",
            ],
            "known_priorities": ["Story arc", "Plain language", "Tension and resolution"],
            "known_skepticisms": ["Corporate speak", "Over-rehearsed answers", "Jargon"],
            "what_impresses_them": ["Vivid anecdotes", "Honest vulnerability", "Clear takeaways"],
            "what_irritates_them": ["Monologues", "Evading personal angle", "Sales pitches"],
            "expertise_areas": ["Long-form interviews", "Audience engagement"],
            "behavioral_signals": ["Mirrors your phrasing", "Summarizes for listeners"],
            "inferred_concerns_by_context": {"media_podcast": ["Listener takeaway", "Controversy balance"]},
            "source_citations": {},
            "confidence": {},
        },
    },
    {
        "file": "aggressive-cross-examiner.json",
        "id": "lib_aggressive_cross_examiner",
        "name": "The Aggressive Cross-Examiner",
        "title": "Senior Counsel",
        "company": "Hartwell & Associates",
        "domain": "negotiation",
        "category": "professional",
        "tags": ["legal", "deposition", "cross-exam"],
        "avatar_brief_template": "Adversarial attorney who pins down timelines, inconsistencies, and admissions under pressure.",
        "profile_json": {
            "communication_style": {
                "directness": "Extremely direct — leading questions",
                "formality": "Courtroom formal",
                "pace": "Rapid-fire with strategic silence",
                "listening_style": "Catalogs contradictions for impeachment",
            },
            "core_values": ["Precision", "Record clarity", "Credibility testing"],
            "typical_question_patterns": [
                "Isn't it true that…",
                "You testified earlier that… how do you reconcile that?",
                "Who else was in the room?",
            ],
            "known_priorities": ["Timeline accuracy", "Document alignment", "Yes/no clarity"],
            "known_skepticisms": ["I don't recall", "Characterizations without facts", "Speculation"],
            "what_impresses_them": ["Precise dates", "Consistent accounts", "Admitting limits"],
            "what_irritates_them": ["Argumentative non-answers", "Narrative drift", "Over-qualifying"],
            "expertise_areas": ["Depositions", "Discovery", "Witness prep"],
            "behavioral_signals": ["Repeats questions", "References prior statements"],
            "inferred_concerns_by_context": {"deposition_legal": ["Credibility", "Document gaps"]},
            "source_citations": {},
            "confidence": {},
        },
    },
    {
        "file": "demanding-board-chair.json",
        "id": "lib_demanding_board_chair",
        "name": "The Demanding Board Chair",
        "title": "Board Chair",
        "company": "Apex Holdings",
        "domain": "fundraising",
        "category": "professional",
        "tags": ["board", "governance", "strategy"],
        "avatar_brief_template": "Seasoned chair who expects strategic clarity, capital discipline, and accountability to the board.",
        "profile_json": {
            "communication_style": {
                "directness": "Executive direct",
                "formality": "Highly formal",
                "pace": "Efficient — low tolerance for rambling",
                "listening_style": "Maps answers to fiduciary duties",
            },
            "core_values": ["Governance", "Shareholder value", "Strategic focus"],
            "typical_question_patterns": [
                "What are the top three risks this quarter?",
                "How does this align with our three-year plan?",
                "What do you need from the board?",
            ],
            "known_priorities": ["Risk oversight", "CEO accountability", "Capital allocation"],
            "known_skepticisms": ["Operational detail without strategy", "Surprises", "Undefined KPIs"],
            "what_impresses_them": ["Clear asks", "Risk mitigations", "Benchmarked KPIs"],
            "what_irritates_them": ["Surprise bad news", "Blame shifting", "Unbounded initiatives"],
            "expertise_areas": ["Board dynamics", "M&A", "Executive compensation"],
            "behavioral_signals": ["Redirects tangents", "Requests one-page summaries"],
            "inferred_concerns_by_context": {"board_meeting": ["Fiduciary risk", "Strategic drift"]},
            "source_citations": {},
            "confidence": {},
        },
    },
    {
        "file": "empathetic-hr-partner.json",
        "id": "lib_empathetic_hr_partner",
        "name": "The Empathetic HR Partner",
        "title": "HR Business Partner",
        "company": "Brightpath Corp",
        "domain": "interview",
        "category": "professional",
        "tags": ["hr", "behavioral", "culture"],
        "avatar_brief_template": "Warm HR partner who explores collaboration, feedback, and values fit while staying structured.",
        "profile_json": {
            "communication_style": {
                "directness": "Gentle but clear",
                "formality": "Approachable professional",
                "pace": "Patient, reflective",
                "listening_style": "Attends to interpersonal dynamics and growth mindset",
            },
            "core_values": ["Psychological safety", "Growth", "Inclusive teamwork"],
            "typical_question_patterns": [
                "Tell me about receiving difficult feedback",
                "How do you support a struggling teammate?",
                "Describe a values conflict you navigated",
            ],
            "known_priorities": ["Collaboration", "Self-awareness", "Ethical judgment"],
            "known_skepticisms": ["Hero narratives", "Blame", "Rigid perfectionism"],
            "what_impresses_them": ["Reflection", "Repair after conflict", "Specific inclusion actions"],
            "what_irritates_them": ["Dismissive tone", "Taking credit for team work", "Avoiding accountability"],
            "expertise_areas": ["Behavioral interviewing", "Culture programs", "Conflict mediation"],
            "behavioral_signals": ["Nods and paraphrases", "Asks how others felt"],
            "inferred_concerns_by_context": {"job_interview": ["Team fit", "Feedback receptivity"]},
            "source_citations": {},
            "confidence": {},
        },
    },
    {
        "file": "impatient-prospect.json",
        "id": "lib_impatient_prospect",
        "name": "The Impatient Prospect",
        "title": "VP Operations",
        "company": "Velocity Logistics",
        "domain": "sales",
        "category": "professional",
        "tags": ["sales", "discovery", "busy-executive"],
        "avatar_brief_template": "Time-starved buyer who wants the problem, proof, and price fast — little patience for feature tours.",
        "profile_json": {
            "communication_style": {
                "directness": "Very direct — interrupts pitches",
                "formality": "Business casual",
                "pace": "Fast",
                "listening_style": "Filters for ROI and implementation burden",
            },
            "core_values": ["Time", "Reliability", "Measurable outcomes"],
            "typical_question_patterns": [
                "Why should I care in the next 90 days?",
                "Who else uses this and what changed?",
                "What's the implementation lift?",
            ],
            "known_priorities": ["Time to value", "Risk reduction", "Vendor stability"],
            "known_skepticisms": ["Feature dumps", "Analyst reports without references", "Long pilots"],
            "what_impresses_them": ["Customer proof", "Clear ROI", "Short pilot plan"],
            "what_irritates_them": ["Slides without agenda", "Jargon", "Avoiding pricing"],
            "expertise_areas": ["Ops efficiency", "Vendor selection", "P&L ownership"],
            "behavioral_signals": ["Checks watch", "Asks for bottom line"],
            "inferred_concerns_by_context": {"sales_discovery": ["Switching cost", "Internal buy-in"]},
            "source_citations": {},
            "confidence": {},
        },
    },
    {
        "file": "technical-deep-dive.json",
        "id": "lib_technical_deep_dive",
        "name": "The Technical Deep-Dive Lead",
        "title": "Principal Engineer",
        "company": "CoreStack",
        "domain": "interview",
        "category": "professional",
        "tags": ["technical", "architecture", "interview"],
        "avatar_brief_template": "Principal engineer who whiteboards architecture, failure modes, and operational trade-offs in depth.",
        "profile_json": {
            "communication_style": {
                "directness": "Technically blunt",
                "formality": "Engineering culture casual",
                "pace": "Deep dives with long silences to think",
                "listening_style": "Tests for first principles and ops reality",
            },
            "core_values": ["Correctness", "Operability", "Elegant trade-offs"],
            "typical_question_patterns": [
                "How does this fail at scale?",
                "Walk me through the data model",
                "What would you monitor in production?",
            ],
            "known_priorities": ["Reliability", "Latency", "Maintainability"],
            "known_skepticisms": ["Resume-driven development", "Magic scaling claims", "Ignoring observability"],
            "what_impresses_them": ["Failure stories", "Metrics and SLOs", "Simple designs"],
            "what_irritates_them": ["Buzzword architecture", "No hands-on depth", "Dismissing edge cases"],
            "expertise_areas": ["Distributed systems", "Databases", "SRE"],
            "behavioral_signals": ["Draws diagrams", "Asks about on-call"],
            "inferred_concerns_by_context": {"job_interview": ["Depth vs breadth", "Production judgment"]},
            "source_citations": {},
            "confidence": {},
        },
    },
    {
        "file": "conflict-avoidant-partner.json",
        "id": "lib_conflict_avoidant_partner",
        "name": "The Conflict-Avoidant Partner",
        "title": "Co-Founder",
        "company": "Home & Hearth Studio",
        "domain": "personal",
        "category": "personal",
        "tags": ["relationship", "difficult-conversation", "personal"],
        "avatar_brief_template": "Co-founder who deflects tension, uses humor, and struggles to name hard feelings directly.",
        "profile_json": {
            "communication_style": {
                "directness": "Indirect — hedges and softens",
                "formality": "Informal intimate",
                "pace": "Uneven — speeds up when uncomfortable",
                "listening_style": "Hears tone more than words; avoids escalation",
            },
            "core_values": ["Harmony", "Loyalty", "Keeping the peace"],
            "typical_question_patterns": [
                "Can we not make this a big thing?",
                "I thought we were fine…",
                "Maybe we're both tired",
            ],
            "known_priorities": ["Avoiding blow-ups", "Maintaining connection", "Short-term calm"],
            "known_skepticisms": ["Absolute language", "Public confrontation", "Long grievance lists"],
            "what_impresses_them": ["Gentle framing", "Shared memories", "Small concrete asks"],
            "what_irritates_them": ["Raised voice", "Ultimatums", "Bringing up old fights"],
            "expertise_areas": ["Creative partnership", "Household logistics"],
            "behavioral_signals": ["Changes subject", "Uses humor to deflect"],
            "inferred_concerns_by_context": {
                "difficult_conversation": ["Being blamed", "Loss of partnership"]
            },
            "source_citations": {},
            "confidence": {},
        },
    },
    {
        "file": "direct-communicator-partner.json",
        "id": "lib_direct_communicator_partner",
        "name": "The Direct Communicator Partner",
        "title": "Spouse",
        "company": None,
        "domain": "personal",
        "category": "personal",
        "tags": ["relationship", "direct", "personal"],
        "avatar_brief_template": "Partner who values clarity and follow-through; expects you to say what you mean without drama.",
        "profile_json": {
            "communication_style": {
                "directness": "Very direct",
                "formality": "Plainspoken",
                "pace": "Steady",
                "listening_style": "Tracks commitments and inconsistencies",
            },
            "core_values": ["Honesty", "Reliability", "Respect"],
            "typical_question_patterns": [
                "What do you actually want?",
                "Did you mean what you said yesterday?",
                "What's the plan — specifically?",
            ],
            "known_priorities": ["Clear agreements", "Follow-through", "No passive aggression"],
            "known_skepticisms": ["Hinting instead of asking", "Moving goalposts", "Victim narratives"],
            "what_impresses_them": ["Owning mistakes", "Specific apologies", "Action plans"],
            "what_irritates_them": ["Silent treatment", "Vague promises", "Deflection"],
            "expertise_areas": ["Household planning", "Long-term partnership"],
            "behavioral_signals": ["Repeats your words back", "Asks for timelines"],
            "inferred_concerns_by_context": {
                "personal_conversation": ["Trust", "Shared responsibilities"]
            },
            "source_citations": {},
            "confidence": {},
        },
    },
    {
        "file": "defensive-partner.json",
        "id": "lib_defensive_partner",
        "name": "The Defensive Partner",
        "title": "Sibling",
        "company": None,
        "domain": "personal",
        "category": "personal",
        "tags": ["family", "defensive", "personal"],
        "avatar_brief_template": "Family member who interprets feedback as criticism and counter-attacks when feeling judged.",
        "profile_json": {
            "communication_style": {
                "directness": "Reactive — escalates when cornered",
                "formality": "Informal family tone",
                "pace": "Quick to interrupt when threatened",
                "listening_style": "Filters for blame and disrespect",
            },
            "core_values": ["Fairness", "Respect", "Not being the villain"],
            "typical_question_patterns": [
                "Why are you attacking me?",
                "You always do this",
                "What about when you…?",
            ],
            "known_priorities": ["Saving face", "Being heard", "Not losing status"],
            "known_skepticisms": ["Generalizations", "Bringing up the past", "Tone policing"],
            "what_impresses_them": ["Acknowledging their intent", "I-statements", "Private settings"],
            "what_irritates_them": ["Public correction", "Sarcasm", "Comparisons to others"],
            "expertise_areas": ["Family dynamics", "Shared history"],
            "behavioral_signals": ["Crosses arms", "Brings up counter-examples"],
            "inferred_concerns_by_context": {
                "difficult_conversation": ["Shame", "Favoritism"]
            },
            "source_citations": {},
            "confidence": {},
        },
    },
    {
        "file": "supportive-parent.json",
        "id": "lib_supportive_parent",
        "name": "The Supportive Parent",
        "title": "Parent",
        "company": None,
        "domain": "personal",
        "category": "personal",
        "tags": ["family", "parent", "supportive"],
        "avatar_brief_template": "Encouraging parent who wants to understand your choices and offers help without heavy judgment.",
        "profile_json": {
            "communication_style": {
                "directness": "Gentle questions",
                "formality": "Warm familial",
                "pace": "Patient",
                "listening_style": "Listens for stress and wellbeing",
            },
            "core_values": ["Safety", "Happiness", "Family connection"],
            "typical_question_patterns": [
                "Are you taking care of yourself?",
                "What would make this easier?",
                "How can we help?",
            ],
            "known_priorities": ["Health", "Stability", "Staying in touch"],
            "known_skepticisms": ["Risky leaps without plan", "Isolation", "Burnout signals"],
            "what_impresses_them": ["Concrete plans", "Asking for advice", "Regular updates"],
            "what_irritates_them": ["Dismissing concern", "One-word answers", "Avoiding family"],
            "expertise_areas": ["Life experience", "Practical support"],
            "behavioral_signals": ["Offers food/help", "References family stories"],
            "inferred_concerns_by_context": {
                "personal_conversation": ["Wellbeing", "Financial security"]
            },
            "source_citations": {},
            "confidence": {},
        },
    },
    {
        "file": "traditional-parent.json",
        "id": "lib_traditional_parent",
        "name": "The Traditional Parent",
        "title": "Parent",
        "company": None,
        "domain": "personal",
        "category": "personal",
        "tags": ["family", "parent", "traditional"],
        "avatar_brief_template": "Parent with conventional expectations about career stability, respect, and family obligations.",
        "profile_json": {
            "communication_style": {
                "directness": "Indirect advice through stories",
                "formality": "Respectful hierarchical",
                "pace": "Measured",
                "listening_style": "Compares choices to family norms and past generations",
            },
            "core_values": ["Respect", "Stability", "Family honor"],
            "typical_question_patterns": [
                "Is this a real job?",
                "What will people think?",
                "When will you settle down?",
            ],
            "known_priorities": ["Financial security", "Respect for elders", "Predictability"],
            "known_skepticisms": ["Unclear career paths", "Moving far away", "Casual attitudes"],
            "what_impresses_them": ["Titles and institutions", "Saving money", "Family participation"],
            "what_irritates_them": ["Dismissive tone", "Breaking traditions", "Unreturned calls"],
            "expertise_areas": ["Family expectations", "Community norms"],
            "behavioral_signals": ["Cites relatives", "Uses proverbs"],
            "inferred_concerns_by_context": {
                "personal_conversation": ["Reputation", "Long-term security"]
            },
            "source_citations": {},
            "confidence": {},
        },
    },
]

os.makedirs(LIB_DIR, exist_ok=True)

for p in PROFILES:
    out = {
        "id": p["id"],
        "name": p["name"],
        "title": p["title"],
        "company": p["company"],
        "domain": p["domain"],
        "category": p["category"],
        "tags": p["tags"],
        "avatar_brief_template": p["avatar_brief_template"],
        "source_urls": [],
        "profile_json": p["profile_json"],
    }
    if p.get("is_featured"):
        out["is_featured"] = True
    path = os.path.join(LIB_DIR, p["file"])
    with open(path, "w", encoding="utf-8") as f:
        json.dump(out, f, indent=2)
        f.write("\n")
    print("wrote", p["file"])

print("done", len(PROFILES), "files")
